name: Notify unified website PoC

on:
  push:
    branches:
      - subdirectory_poc

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.POC_PAT_TOKEN }}" \
            https://api.github.com/repos/mlinpl/mlinpl_submodules_poc/dispatches \
            -d '{"event_type":"submodule_update"}'
